<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>10. Predictive models: prep, train, test, and evaluate • Text as Data Resources</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/cosmo/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><link href="../extra.css" rel="stylesheet">
<script src="../extra.js"></script><meta property="og:title" content="10. Predictive models: prep, train, test, and evaluate">
<meta property="og:description" content="tadr">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">Text as Data Resources</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.1.1</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/index.html">Articles</a>
</li>
<li>
  <a href="../tutorials/index.html">Tutorials</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li>
  <a href="https://github.com/lin380/tadr">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="recipe_10_files/header-attrs-2.10/header-attrs.js"></script><script src="recipe_10_files/jquery-1.11.3/jquery.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1">
<link href="recipe_10_files/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet">
<script src="recipe_10_files/bootstrap-3.3.5/js/bootstrap.min.js"></script><script src="recipe_10_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script><script src="recipe_10_files/bootstrap-3.3.5/shim/respond.min.js"></script><style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="recipe_10_files/navigation-1.1/tabsets.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>10. Predictive models: prep, train, test, and evaluate</h1>
            
      
      <small class="dont-index">Source: <a href="https://github.com/lin380/tadr/blob/master/vignettes/recipe_10.Rmd"><code>vignettes/recipe_10.Rmd</code></a></small>
      <div class="hidden name"><code>recipe_10.Rmd</code></div>

    </div>

    
    
<div id="overview" class="section level2">
<h2 class="hasAnchor">
<a href="#overview" class="anchor"></a>Overview</h2>
<p>In this Recipe we will build a predictive model that will work as a spam filter. The data we will work with are SMS (Short Message Service) text messages from the <a href="http://www.dt.fee.unicamp.br/~tiago/smsspamcollection/">SMS Spam Collection</a> <span class="citation">(<a href="#ref-Almeida2011" role="doc-biblioref">Almeida and G’omez Hildago 2011</a>)</span>. The process steps will include preparing the dataset, splitting it into training and testing sets, building a training model, testing the model, and evaluating the results. We will use the Quanteda package <span class="citation">(<a href="#ref-R-quanteda" role="doc-biblioref">Benoit et al. 2021</a>)</span> as it is a package that facilitates preparing, modeling, and exploring text models.</p>
<p>Let’s load the packages we will use in this Recipe.</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span>           <span class="co"># data manipulation</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://quanteda.io">quanteda</a></span><span class="op">)</span>            <span class="co"># tokenization and document-frequency matrices</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://quanteda.io">quanteda.textstats</a></span><span class="op">)</span>  <span class="co"># descriptive text statistics</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/quanteda/quanteda.textmodels">quanteda.textmodels</a></span><span class="op">)</span> <span class="co"># naive bayes classifier</span></code></pre></div>
</div>
<div id="coding-strategies" class="section level2">
<h2 class="hasAnchor">
<a href="#coding-strategies" class="anchor"></a>Coding strategies</h2>
</div>
<div id="orientation" class="section level2">
<h2 class="hasAnchor">
<a href="#orientation" class="anchor"></a>Orientation</h2>
<p>Let’s first read in a become familiar with the SMS dataset. We can access this dataset through the tadr package.</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sms_df</span> <span class="op">&lt;-</span> <span class="fu">tadr</span><span class="fu">::</span><span class="va"><a href="../reference/sms.html">sms</a></span>  <span class="co"># load dataset from tadr package</span>
<span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">sms_df</span><span class="op">)</span>  <span class="co"># preview dataset structure</span></code></pre></div>
<pre><code>## Rows: 5,574
## Columns: 2
## $ sms_type &lt;chr&gt; "ham", "ham", "spam", "ham", "ham", "spam", "ham", "ham", "sp…
## $ message  &lt;chr&gt; "Go until jurong point, crazy.. Available only in bugis n gre…</code></pre>
<p>The <code>sms_df</code> object is a data frame with 5,574 observations and two columns. The observations correspond to individual text messages. <code>sms_type</code> reflects the type of SMS message; either legitimate (‘ham’) or spam and the <code>message</code> contains the message text.</p>
<div class="tip">
<p>In this recipe I will be suffixing the object names to reflect the object type. We will work with our dataset in four main formats: data frame (<code>_df</code>), corpus <code>_corpus</code>, tokens <code>_tokens</code>, and document-frequency matrix (<code>_dfm</code>).</p>
</div>
<p>Let’s see the proportion of spam to ham messages in our dataset. I will use the <code><a href="https://rdrr.io/pkg/janitor/man/tabyl.html">tabyl()</a></code> function from the janitor package to get the counts and proportions.</p>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sms_df</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span>
    <span class="fu">janitor</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/janitor/man/tabyl.html">tabyl</a></span><span class="op">(</span><span class="va">sms_type</span><span class="op">)</span></code></pre></div>
<div class="kable-table">
<table class="table">
<thead><tr class="header">
<th align="left">sms_type</th>
<th align="right">n</th>
<th align="right">percent</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">ham</td>
<td align="right">4827</td>
<td align="right">0.866</td>
</tr>
<tr class="even">
<td align="left">spam</td>
<td align="right">747</td>
<td align="right">0.134</td>
</tr>
</tbody>
</table>
</div>
<p>So now we know a majority of the messages are ‘ham,’ around 87% to be exact.</p>
<div id="preparation" class="section level3">
<h3 class="hasAnchor">
<a href="#preparation" class="anchor"></a>Preparation</h3>
<!-- data frame to Corpus object -->
<p>We will now create a Quanteda corpus object our of our <code>sms_df</code> data frame. A corpus object is a complex R object which will allow us to manipulate the data and maintain metadata in an accessible format. To create a corpus object all we need to do is call the <code><a href="https://quanteda.io/reference/corpus.html">corpus()</a></code> function and set the <code>text_field</code> argument to identify the column where the text is.</p>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sms_corpus</span> <span class="op">&lt;-</span> <span class="co"># quanteda corpus object</span>
  <span class="fu"><a href="https://quanteda.io/reference/corpus.html">corpus</a></span><span class="op">(</span><span class="va">sms_df</span>, <span class="co"># data frame</span>
         text_field <span class="op">=</span> <span class="st">"message"</span><span class="op">)</span> <span class="co"># text field</span>

<span class="va">sms_corpus</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">5</span><span class="op">)</span> <span class="co"># preview corpus object</span></code></pre></div>
<div class="kable-table">
<table class="table">
<thead><tr class="header">
<th align="left">Text</th>
<th align="right">Types</th>
<th align="right">Tokens</th>
<th align="right">Sentences</th>
<th align="left">sms_type</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">text1</td>
<td align="right">22</td>
<td align="right">29</td>
<td align="right">3</td>
<td align="left">ham</td>
</tr>
<tr class="even">
<td align="left">text2</td>
<td align="right">7</td>
<td align="right">12</td>
<td align="right">2</td>
<td align="left">ham</td>
</tr>
<tr class="odd">
<td align="left">text3</td>
<td align="right">33</td>
<td align="right">37</td>
<td align="right">2</td>
<td align="left">spam</td>
</tr>
<tr class="even">
<td align="left">text4</td>
<td align="right">10</td>
<td align="right">17</td>
<td align="right">2</td>
<td align="left">ham</td>
</tr>
<tr class="odd">
<td align="left">text5</td>
<td align="right">13</td>
<td align="right">14</td>
<td align="right">1</td>
<td align="left">ham</td>
</tr>
</tbody>
</table>
</div>
<p>The <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> function provides an overview of the dataset including some calculated text statistics (‘Types,’ ‘Tokens,’ and ‘Sentences’) as well as metadata. In corpus objects the metadata is known as document variables, or ‘docvars.’ We can access the document variables directly with the <code><a href="https://quanteda.io/reference/docvars.html">docvars()</a></code> function.</p>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sms_corpus</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># corpus object</span>
  <span class="fu"><a href="https://quanteda.io/reference/docvars.html">docvars</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span>  <span class="co"># get corpus metadata attributes</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/slice.html">slice_head</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">5</span><span class="op">)</span> <span class="co"># first observations</span></code></pre></div>
<div class="kable-table">
<table class="table">
<thead><tr class="header">
<th align="left">sms_type</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">ham</td>
</tr>
<tr class="even">
<td align="left">ham</td>
</tr>
<tr class="odd">
<td align="left">spam</td>
</tr>
<tr class="even">
<td align="left">ham</td>
</tr>
<tr class="odd">
<td align="left">ham</td>
</tr>
</tbody>
</table>
</div>
<p>We can add metadata to our corpus object by simply making reference to a new column and assigning values to it. In our data we are going to want to have a unique document id for each of our 4,837 text messages. We want to create a vector of numbers 1 to 4,837. One way to do this is by using the <code>1:4837</code> syntax with the number hardcoded in. Another more flexible way to create the document id vector that is exactly fit to the number of observations is by using the <code><a href="https://quanteda.io/reference/ndoc.html">ndoc()</a></code> function on the corpus object itself. <code><a href="https://quanteda.io/reference/ndoc.html">ndoc()</a></code> will return the number of documents in the corpus object. For corpus objects observations are known as documents and for us a document is a text message.</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sms_corpus</span><span class="op">$</span><span class="va">doc_id</span> <span class="op">&lt;-</span> <span class="co"># create a new column `doc_id`</span>
  <span class="fl">1</span><span class="op">:</span><span class="fu"><a href="https://quanteda.io/reference/ndoc.html">ndoc</a></span><span class="op">(</span><span class="va">sms_corpus</span><span class="op">)</span> <span class="co"># add numeric id to each text message</span></code></pre></div>
<p>We can now look at the document variables again and we will see that the <code>do c_id</code> column now appears.</p>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sms_corpus</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># corpus object</span>
  <span class="fu"><a href="https://quanteda.io/reference/docvars.html">docvars</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span>  <span class="co"># get corpus metadata attributes</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/slice.html">slice_head</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">5</span><span class="op">)</span> <span class="co"># first observations</span></code></pre></div>
<div class="kable-table">
<table class="table">
<thead><tr class="header">
<th align="left">sms_type</th>
<th align="right">doc_id</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">ham</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">ham</td>
<td align="right">2</td>
</tr>
<tr class="odd">
<td align="left">spam</td>
<td align="right">3</td>
</tr>
<tr class="even">
<td align="left">ham</td>
<td align="right">4</td>
</tr>
<tr class="odd">
<td align="left">ham</td>
<td align="right">5</td>
</tr>
</tbody>
</table>
</div>
<p>Of note, if at any time we would like to convert our corpus object back into a data frame we can use the <code><a href="https://generics.r-lib.org/reference/tidy.html">tidy()</a></code> function from the tidytext package.</p>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sms_corpus</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># corpus object</span>
  <span class="fu">tidytext</span><span class="fu">::</span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># convert back to a data frame</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/slice.html">slice_head</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">5</span><span class="op">)</span> <span class="co"># first observations</span></code></pre></div>
<div class="kable-table">
<table class="table">
<colgroup>
<col width="90%">
<col width="5%">
<col width="4%">
</colgroup>
<thead><tr class="header">
<th align="left">text</th>
<th align="left">sms_type</th>
<th align="right">doc_id</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">Go until jurong point, crazy.. Available only in bugis n great world la e buffet… Cine there got amore wat…</td>
<td align="left">ham</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">Ok lar… Joking wif u oni…</td>
<td align="left">ham</td>
<td align="right">2</td>
</tr>
<tr class="odd">
<td align="left">Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&amp;C’s apply 08452810075over18’s</td>
<td align="left">spam</td>
<td align="right">3</td>
</tr>
<tr class="even">
<td align="left">U dun say so early hor… U c already then say…</td>
<td align="left">ham</td>
<td align="right">4</td>
</tr>
<tr class="odd">
<td align="left">Nah I don’t think he goes to usf, he lives around here though</td>
<td align="left">ham</td>
<td align="right">5</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="feature-engineering" class="section level3">
<h3 class="hasAnchor">
<a href="#feature-engineering" class="anchor"></a>Feature engineering</h3>
<!-- tokenization and document-frequency matrix -->
<p>The next step towards preparing our dataset for use in the predictive model is to decide what the features are that will be used to help the predictive model learn how to distinguish between spam and ham text messages. To create language features we will tokenize the text into smaller linguistic units. We can choose from characters, words, or sentences, or ngram sequences of either characters of words. For many predictive models, the default feature to select as a starting point will be words. However, it there is reason to believe that some other linguistic unit(s) would make more practical sense there is nothing limiting you from selecting another unit. If we later see that the model does not perform well we can always come back and tweak the tokenization process and try other linguistic units.</p>
<p>Let’s move forward by tokenizing the messages into words. We will also remove punctuation and numbers and lowercase all the messages. The <code><a href="https://quanteda.io/reference/tokens.html">tokens()</a></code> function allows us to do all but lowercasing.</p>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sms_tokens</span> <span class="op">&lt;-</span> 
  <span class="fu"><a href="https://quanteda.io/reference/tokens.html">tokens</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">sms_corpus</span>, <span class="co"># corpus object</span>
         what <span class="op">=</span> <span class="st">"word"</span>, <span class="co"># tokenize by words</span>
         remove_punct <span class="op">=</span> <span class="cn">TRUE</span>, <span class="co"># remove punctuation</span>
         remove_numbers <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="co"># remove numbers</span></code></pre></div>
<p>The result assigned to <code>sms_tokens</code> is a ‘tokens’ object. Looking a the first few messages we can see that they have been tokenized into words.</p>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sms_tokens</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span>
    <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">5</span><span class="op">)</span>  <span class="co"># preview first 5 tokenized messages</span></code></pre></div>
<pre><code>## Tokens consisting of 5 documents and 2 docvars.
## text1 :
##  [1] "Go"        "until"     "jurong"    "point"     "crazy"     "Available"
##  [7] "only"      "in"        "bugis"     "n"         "great"     "world"    
## [ ... and 8 more ]
## 
## text2 :
## [1] "Ok"     "lar"    "Joking" "wif"    "u"      "oni"   
## 
## text3 :
##  [1] "Free"  "entry" "in"    "2"     "a"     "wkly"  "comp"  "to"    "win"  
## [10] "FA"    "Cup"   "final"
## [ ... and 20 more ]
## 
## text4 :
##  [1] "U"       "dun"     "say"     "so"      "early"   "hor"     "U"      
##  [8] "c"       "already" "then"    "say"    
## 
## text5 :
##  [1] "Nah"    "I"      "don't"  "think"  "he"     "goes"   "to"     "usf"   
##  [9] "he"     "lives"  "around" "here"  
## [ ... and 1 more ]</code></pre>
<div class="tip">
<p>The <code><a href="https://rdrr.io/r/utils/head.html">head()</a></code> function has been used here instead of the <code><a href="https://dplyr.tidyverse.org/reference/slice.html">slice_head()</a></code> function we have typically used. It is of note that <code><a href="https://rdrr.io/r/utils/head.html">head()</a></code> works much like <code><a href="https://dplyr.tidyverse.org/reference/slice.html">slice_head()</a></code> with the main distinction that <code><a href="https://dplyr.tidyverse.org/reference/slice.html">slice_head()</a></code> only works on data frame objects where <code><a href="https://rdrr.io/r/utils/head.html">head()</a></code> will work on any type of R object. In this case <code>sms_tokens</code> is a ‘tokens’ object which is a more complex type of list object.</p>
</div>
<p>What is nice about a tokens object is that the metadata from the corpus object <code>sms_corpus</code> is retained. We can preview the metadata with.</p>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sms_tokens</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://quanteda.io/reference/docvars.html">docvars</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span>  <span class="co"># get corpus metadata attributes</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/slice.html">slice_head</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">5</span><span class="op">)</span> <span class="co"># first observations</span></code></pre></div>
<div class="kable-table">
<table class="table">
<thead><tr class="header">
<th align="left">sms_type</th>
<th align="right">doc_id</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">ham</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">ham</td>
<td align="right">2</td>
</tr>
<tr class="odd">
<td align="left">spam</td>
<td align="right">3</td>
</tr>
<tr class="even">
<td align="left">ham</td>
<td align="right">4</td>
</tr>
<tr class="odd">
<td align="left">ham</td>
<td align="right">5</td>
</tr>
</tbody>
</table>
</div>
<p>It is good to know that these document variables can be used to group (<code><a href="https://quanteda.io/reference/tokens_group.html">tokens_group()</a></code>), subset (<code><a href="https://quanteda.io/reference/tokens_subset.html">tokens_subset()</a></code>), and sample (<code><a href="https://quanteda.io/reference/tokens_sample.html">tokens_sample()</a></code>) the <code>sms_tokens</code> object much like functions from the tidyverse package when working with data frames.</p>
<p>There are a number of other functions which can be used to manipulate the tokens themselves inside the tokens object (<code><a href="https://quanteda.io/reference/tokens_ngrams.html">tokens_ngrams()</a></code>, <code><a href="https://quanteda.io/reference/tokens_tolower.html">tokens_toupper()</a></code>, etc.). For our purposes we will use one of these functions named <code><a href="https://quanteda.io/reference/tokens_tolower.html">tokens_tolower()</a></code> which will lowercase all the tokens.</p>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sms_tokens</span> <span class="op">&lt;-</span> 
  <span class="va">sms_tokens</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># </span>
  <span class="fu"><a href="https://quanteda.io/reference/tokens_tolower.html">tokens_tolower</a></span><span class="op">(</span><span class="op">)</span> <span class="co"># lowercase all characters</span>

<span class="va">sms_tokens</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">5</span><span class="op">)</span> <span class="co"># preview first 5 tokenized messages</span></code></pre></div>
<pre><code>## Tokens consisting of 5 documents and 2 docvars.
## text1 :
##  [1] "go"        "until"     "jurong"    "point"     "crazy"     "available"
##  [7] "only"      "in"        "bugis"     "n"         "great"     "world"    
## [ ... and 8 more ]
## 
## text2 :
## [1] "ok"     "lar"    "joking" "wif"    "u"      "oni"   
## 
## text3 :
##  [1] "free"  "entry" "in"    "2"     "a"     "wkly"  "comp"  "to"    "win"  
## [10] "fa"    "cup"   "final"
## [ ... and 20 more ]
## 
## text4 :
##  [1] "u"       "dun"     "say"     "so"      "early"   "hor"     "u"      
##  [8] "c"       "already" "then"    "say"    
## 
## text5 :
##  [1] "nah"    "i"      "don't"  "think"  "he"     "goes"   "to"     "usf"   
##  [9] "he"     "lives"  "around" "here"  
## [ ... and 1 more ]</code></pre>
<p>Now we have our tokens ready that we will use as features in our prediction model.</p>
<p>The next step is to create a Document-Frequency Matrix (DFM). In this structure each unique token has a column and each unique document a row. The values are the (raw) counts of each of the tokens for each of the documents. To create a DFM we use the <code><a href="https://quanteda.io/reference/dfm.html">dfm()</a></code> function.</p>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sms_dfm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://quanteda.io/reference/dfm.html">dfm</a></span><span class="op">(</span><span class="va">sms_tokens</span><span class="op">)</span>  <span class="co"># create a document-frequency matrix</span>

<span class="va">sms_dfm</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span>
    <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">5</span><span class="op">)</span>  <span class="co"># preview first 5 documents in the dfm</span></code></pre></div>
<pre><code>## Document-feature matrix of: 5 documents, 9,313 features (99.84% sparse) and 2 docvars.
##        features
## docs    go until jurong point crazy available only in bugis n
##   text1  1     1      1     1     1         1    1  1     1 1
##   text2  0     0      0     0     0         0    0  0     0 0
##   text3  0     0      0     0     0         0    0  1     0 0
##   text4  0     0      0     0     0         0    0  0     0 0
##   text5  0     0      0     0     0         0    0  0     0 0
## [ reached max_nfeat ... 9,303 more features ]</code></pre>
<p>The preview shows some key information about our <code>sms_dfm</code> object. Our preview only contains 5 documents, but 9,313 features. The features are the number of unique tokens in the matrix. Each document will have the number of times each unique token appeared in a message as a value. Since only a subset of the 9,313 possible feature tokens will appear in any given message this means that may values will be 0. The relative amount of zeros to non-zeros is called sparsity. In the preview we also see that our matrix is 99.84% sparse. This is not uncommon but in cases where there the features number in the 10s of thousands (also not uncommon) the matrix will become quite large and incur processing and memory costs that may need to be taken into account.</p>
<div class="tip">
<p>Our matrix is not unwieldly at it’s current size so we won’t ‘trim’ it, but it is good to know that quanteda provides a <code><a href="https://quanteda.io/reference/dfm_trim.html">dfm_trim()</a></code> function that can be used to trim features that either do not have a certain frequency count threshold (usually minimum frequency <code>min_termfreq =</code>) or are sparse (column-wise) to a certain percentage (<code>sparsity =</code>).</p>
</div>
<p>Let’s explore the features in our DFM. We can use the <code><a href="https://quanteda.io/reference/topfeatures.html">topfeatures()</a></code> function to retrieve the most frequent features in the <code>sms_dfm</code> object.</p>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sms_dfm</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span>
    <span class="fu"><a href="https://quanteda.io/reference/topfeatures.html">topfeatures</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">10</span><span class="op">)</span></code></pre></div>
<pre><code>##    i   to  you    a  the    u  and   is   in   me 
## 2298 2252 2145 1446 1335 1168  979  895  891  800</code></pre>
<p>We can also use the <code><a href="https://quanteda.io/reference/textstat_frequency.html">textstat_frequency()</a></code> function from the quanteda.textstats package to get frequency measures as well as group these statistics by a document variable. In this case let’s look at the frequency statistics for both spam and ham SMS types.</p>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sms_dfm</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://quanteda.io/reference/textstat_frequency.html">textstat_frequency</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">5</span>, <span class="co"># get top 5 features</span>
                     groups <span class="op">=</span> <span class="va">sms_type</span><span class="op">)</span> <span class="co"># group by sms_type</span></code></pre></div>
<div class="kable-table">
<table class="table">
<thead><tr class="header">
<th align="left">feature</th>
<th align="right">frequency</th>
<th align="right">rank</th>
<th align="right">docfreq</th>
<th align="left">group</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">i</td>
<td align="right">2252</td>
<td align="right">1</td>
<td align="right">1609</td>
<td align="left">ham</td>
</tr>
<tr class="even">
<td align="left">you</td>
<td align="right">1855</td>
<td align="right">2</td>
<td align="right">1295</td>
<td align="left">ham</td>
</tr>
<tr class="odd">
<td align="left">to</td>
<td align="right">1562</td>
<td align="right">3</td>
<td align="right">1219</td>
<td align="left">ham</td>
</tr>
<tr class="even">
<td align="left">the</td>
<td align="right">1131</td>
<td align="right">4</td>
<td align="right">867</td>
<td align="left">ham</td>
</tr>
<tr class="odd">
<td align="left">a</td>
<td align="right">1067</td>
<td align="right">5</td>
<td align="right">883</td>
<td align="left">ham</td>
</tr>
<tr class="even">
<td align="left">to</td>
<td align="right">690</td>
<td align="right">1</td>
<td align="right">467</td>
<td align="left">spam</td>
</tr>
<tr class="odd">
<td align="left">a</td>
<td align="right">379</td>
<td align="right">2</td>
<td align="right">295</td>
<td align="left">spam</td>
</tr>
<tr class="even">
<td align="left">call</td>
<td align="right">346</td>
<td align="right">3</td>
<td align="right">319</td>
<td align="left">spam</td>
</tr>
<tr class="odd">
<td align="left">£</td>
<td align="right">324</td>
<td align="right">4</td>
<td align="right">253</td>
<td align="left">spam</td>
</tr>
<tr class="even">
<td align="left">you</td>
<td align="right">290</td>
<td align="right">5</td>
<td align="right">238</td>
<td align="left">spam</td>
</tr>
</tbody>
</table>
</div>
<p>We can see that our grouped frequency statistics show similarities and differences. On the one hand we can see that the frequency counts and document frequency are much larger for ham. This makes sense since around 87% of the messages are ham in our dataset. On the other hand, if we look at particular features we see that ‘i’ is the most common feature for ham and ‘to’ for spam. There is some overlap as well ‘you’ and ‘a’ appear in both ham and spam. The more overlap we have between features the less distinctive our classes (ham and spam) will be which can make it more difficult for the prediction model to make accurate predictions.</p>
<p>For the moment we will continue to move forward and see how the model does despite these similarities, but it is important to know that we can apply some techniques to reduce similarity. One way is to return to our tokenization process and remove common words using a stopword list. This approach is common but relies on pre-defined lists of what is considered common. Another approach is to weigh the distribution of the given dataset such that the number of documents a feature appears in influences the feature value. This weighting is called the <a href="https://en.wikipedia.org/wiki/Tf%E2%80%93idf">Term Frequency-Inverse Document Frequency (TF-IDF)</a>. We can use the <code><a href="https://quanteda.io/reference/dfm_tfidf.html">dfm_tfidf()</a></code> function to transform the <code>sms_dfm</code> matrix and view how this weighting effects our apparent overlap in top features for ham and spam.</p>
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sms_dfm</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://quanteda.io/reference/dfm_tfidf.html">dfm_tfidf</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># calculate term frequency-inverse document frequency weighted scores</span>
  <span class="fu"><a href="https://quanteda.io/reference/textstat_frequency.html">textstat_frequency</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">5</span>, <span class="co"># get top 5 features</span>
                     groups <span class="op">=</span> <span class="va">sms_type</span>, <span class="co"># group by sms_type</span>
                     force <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="co"># force calculation despite weights</span></code></pre></div>
<div class="kable-table">
<table class="table">
<thead><tr class="header">
<th align="left">feature</th>
<th align="right">frequency</th>
<th align="right">rank</th>
<th align="right">docfreq</th>
<th align="left">group</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">i</td>
<td align="right">1193</td>
<td align="right">1</td>
<td align="right">1609</td>
<td align="left">ham</td>
</tr>
<tr class="even">
<td align="left">you</td>
<td align="right">1040</td>
<td align="right">2</td>
<td align="right">1295</td>
<td align="left">ham</td>
</tr>
<tr class="odd">
<td align="left">u</td>
<td align="right">834</td>
<td align="right">3</td>
<td align="right">702</td>
<td align="left">ham</td>
</tr>
<tr class="even">
<td align="left">the</td>
<td align="right">828</td>
<td align="right">4</td>
<td align="right">867</td>
<td align="left">ham</td>
</tr>
<tr class="odd">
<td align="left">to</td>
<td align="right">811</td>
<td align="right">5</td>
<td align="right">1219</td>
<td align="left">ham</td>
</tr>
<tr class="even">
<td align="left">£</td>
<td align="right">432</td>
<td align="right">1</td>
<td align="right">253</td>
<td align="left">spam</td>
</tr>
<tr class="odd">
<td align="left">to</td>
<td align="right">358</td>
<td align="right">2</td>
<td align="right">467</td>
<td align="left">spam</td>
</tr>
<tr class="even">
<td align="left">call</td>
<td align="right">351</td>
<td align="right">3</td>
<td align="right">319</td>
<td align="left">spam</td>
</tr>
<tr class="odd">
<td align="left">free</td>
<td align="right">305</td>
<td align="right">4</td>
<td align="right">168</td>
<td align="left">spam</td>
</tr>
<tr class="even">
<td align="left">your</td>
<td align="right">258</td>
<td align="right">5</td>
<td align="right">227</td>
<td align="left">spam</td>
</tr>
</tbody>
</table>
</div>
<p>We can see now that the TF-IDF scores have reduced the apparent overlap. Let’s keep this in mind when we evaluate our model performance. For now we will continue with the raw counts as our value scores.</p>
<p>The last step we need to do to prepare our dataset for predictive modeling is to split the dataset into training and testing sets. The training set should contain around 75% of the dataset and the other 25% will be reserve for testing. Both datasets should have similar relative proportions of the classes we want to predict (i.e. ham and spam).</p>
<p>Let’s create a numeric vector which we will use to randomly sample 75% of the observations from our <code>sms_dfm</code> for use in training. First I will set a random number seed <code>set.seed(300)</code> to make this example reproducible. Next I will calculate the number of documents in the <code>sms_dfm</code> with the <code><a href="https://quanteda.io/reference/ndoc.html">ndoc()</a></code> function. then I will multiply this number by <code>.75</code> to get the sample size we want. The we can use the <code><a href="https://rdrr.io/r/base/sample.html">sample()</a></code> function to get the <code>train_ids</code>. Note we set <code>replace = FALSE</code> so no ids are repeated in the sample (all 75% will be unique).</p>
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">300</span><span class="op">)</span> <span class="co"># make reproducible</span>

<span class="va">num_docs</span> <span class="op">&lt;-</span> 
  <span class="va">sms_dfm</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># dfm object</span>
  <span class="fu"><a href="https://quanteda.io/reference/ndoc.html">ndoc</a></span><span class="op">(</span><span class="op">)</span> <span class="co"># get number of documents</span>

<span class="va">train_size</span> <span class="op">&lt;-</span> 
  <span class="op">(</span><span class="va">num_docs</span> <span class="op">*</span> <span class="fl">.75</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># get size of sample</span>
  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="op">)</span> <span class="co"># round to nearest whole number</span>

<span class="va">train_ids</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="va">num_docs</span>, <span class="co"># population</span>
                   size <span class="op">=</span> <span class="va">train_size</span>, <span class="co"># size of sample</span>
                   replace <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="co"># without replacement</span>

<span class="va">train_ids</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">10</span><span class="op">)</span></code></pre></div>
<pre><code>##  [1] 2638  874 3650 3740  789  553 1705 4368 4557 2828</code></pre>
<p>With our training ids <code>train_ids</code> we can now subset the <code>sms_dfm</code> into a training set and a test set.</p>
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sms_dfm_train</span> <span class="op">&lt;-</span> 
  <span class="va">sms_dfm</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># dfm object</span>
  <span class="fu"><a href="https://quanteda.io/reference/dfm_subset.html">dfm_subset</a></span><span class="op">(</span><span class="va">doc_id</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="va">train_ids</span><span class="op">)</span> <span class="co"># subset matching doc_id and train_ids</span>

<span class="va">sms_dfm_test</span> <span class="op">&lt;-</span> 
  <span class="va">sms_dfm</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># dfm object</span>
  <span class="fu"><a href="https://quanteda.io/reference/dfm_subset.html">dfm_subset</a></span><span class="op">(</span><span class="op">!</span><span class="va">doc_id</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="va">train_ids</span><span class="op">)</span> <span class="co"># subset non-matching doc_id and train_ids</span></code></pre></div>
<p>Let’s verify that the proportions of ham to spam are similar between the <code>sms_dfm_train</code> and <code>sms_dfm_test</code> sets. Again, I will use the <code><a href="https://rdrr.io/pkg/janitor/man/tabyl.html">tabyl()</a></code> function.</p>
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sms_dfm</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># dfm object</span>
  <span class="fu"><a href="https://quanteda.io/reference/docvars.html">docvars</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># pull the document variables</span>
  <span class="fu">janitor</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/janitor/man/tabyl.html">tabyl</a></span><span class="op">(</span><span class="va">sms_type</span><span class="op">)</span> <span class="co"># check ham/spam proportions</span></code></pre></div>
<div class="kable-table">
<table class="table">
<thead><tr class="header">
<th align="left">sms_type</th>
<th align="right">n</th>
<th align="right">percent</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">ham</td>
<td align="right">4827</td>
<td align="right">0.866</td>
</tr>
<tr class="even">
<td align="left">spam</td>
<td align="right">747</td>
<td align="right">0.134</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sms_dfm_train</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># dfm object</span>
  <span class="fu"><a href="https://quanteda.io/reference/docvars.html">docvars</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># pull the document variables</span>
  <span class="fu">janitor</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/janitor/man/tabyl.html">tabyl</a></span><span class="op">(</span><span class="va">sms_type</span><span class="op">)</span> <span class="co"># check ham/spam proportions</span></code></pre></div>
<div class="kable-table">
<table class="table">
<thead><tr class="header">
<th align="left">sms_type</th>
<th align="right">n</th>
<th align="right">percent</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">ham</td>
<td align="right">3626</td>
<td align="right">0.867</td>
</tr>
<tr class="even">
<td align="left">spam</td>
<td align="right">554</td>
<td align="right">0.133</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sms_dfm_test</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># dfm object</span>
  <span class="fu"><a href="https://quanteda.io/reference/docvars.html">docvars</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># pull the document variables</span>
  <span class="fu">janitor</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/janitor/man/tabyl.html">tabyl</a></span><span class="op">(</span><span class="va">sms_type</span><span class="op">)</span> <span class="co"># check ham/spam proportions</span></code></pre></div>
<div class="kable-table">
<table class="table">
<thead><tr class="header">
<th align="left">sms_type</th>
<th align="right">n</th>
<th align="right">percent</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">ham</td>
<td align="right">1201</td>
<td align="right">0.862</td>
</tr>
<tr class="even">
<td align="left">spam</td>
<td align="right">193</td>
<td align="right">0.138</td>
</tr>
</tbody>
</table>
</div>
<p>The splits look comparable so we are good to proceed to training our prediction model.</p>
</div>
<div id="model-training" class="section level3">
<h3 class="hasAnchor">
<a href="#model-training" class="anchor"></a>Model training</h3>
<!-- naive bayes text modeling -->
<p>We will be using a <a href="https://en.wikipedia.org/wiki/Naive_Bayes_classifier">Naive Bayes Classifier algorithm</a> implemented in the quanteda.textmodels package <code><a href="https://rdrr.io/pkg/quanteda.textmodels/man/textmodel_nb.html">textmodel_nb()</a></code>. Naive Bayes is a common starting algorithm for text classification. To train our mmodel we need to pass the <code>sms_dfm_train</code> document-feature matrix which contains the values for each of our feature tokens to <code>x</code> and then the class labels (‘ham’ and ‘spam’) for each document using the document variables of the <code>sms_dfm_train</code> object. We will assign the model to <code>nb1</code> and use <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> to see an overview of the training results.</p>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">nb1</span> <span class="op">&lt;-</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/quanteda.textmodels/man/textmodel_nb.html">textmodel_nb</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">sms_dfm_train</span>, <span class="co"># document-feature matrix</span>
               y <span class="op">=</span> <span class="va">sms_dfm_train</span><span class="op">$</span><span class="va">sms_type</span><span class="op">)</span> <span class="co"># class labels</span>

<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">nb1</span><span class="op">)</span> <span class="co"># model summary</span></code></pre></div>
<pre><code>## 
## Call:
## textmodel_nb.dfm(x = sms_dfm_train, y = sms_dfm_train$sms_type)
## 
## Class Priors:
## (showing first 2 elements)
##  ham spam 
##  0.5  0.5 
## 
## Estimated Feature Scores:
##           go    until   jurong    point   crazy available    only     in
## ham  0.00323 0.000308 3.24e-05 1.62e-04 0.00013  0.000195 0.00159 0.0100
## spam 0.00104 0.000260 4.33e-05 4.33e-05 0.00026  0.000173 0.00303 0.0023
##         bugis       n    great    world       la        e   buffet     cine
## ham  1.14e-04 0.00180 0.001282 4.38e-04 9.73e-05 0.000973 3.24e-05 9.73e-05
## spam 4.33e-05 0.00039 0.000476 4.33e-05 4.33e-05 0.000217 4.33e-05 4.33e-05
##        there      got    amore      wat       ok      lar   joking      wif
## ham  0.00219 0.002920 3.24e-05 1.22e-03 0.003585 4.87e-04 6.49e-05 3.57e-04
## spam 0.00052 0.000217 4.33e-05 8.66e-05 0.000173 4.33e-05 4.33e-05 4.33e-05
##            u      oni     free    entry       2      a
## ham  0.01293 6.49e-05 0.000811 1.62e-05 0.00396 0.0133
## spam 0.00533 4.33e-05 0.007233 8.66e-04 0.00585 0.0118</code></pre>
<p>In the <code>nb1</code> model summary we see the ‘Call,’ the ‘Class Priors’ and a preview of the ‘Estimated Feature Scores.’ The class priors are set to 50/50 for ham and spam which means our model does not assume one class is more prevalent than the other. We will leave it this way as we don’t want to bias our model towards one class over the other –even though our input data is biased. The posterior probabilities for the features can be seen in the estimated feature scores. For a given word we can see how the model weigh individual features towards ham or spam. Our predictions will be based on the sum of these probabilities for the features in the testing dataset. We can see, for example, the probability of ‘u’ is higher for ham and ‘free’ leans towards ‘spam.’ A feature like ‘a,’ however, does not have much discriminatory power as it is split quite equally.</p>
<p>We can explore more of the feature probabilities using the <code><a href="https://rdrr.io/r/stats/coef.html">coef()</a></code> function on the <code>nb1</code> model.</p>
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">nb1</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># get the feature coefficient scores</span>
  <span class="va">head</span> <span class="co"># preview the feature coefficient scores</span></code></pre></div>
<pre><code>##                ham     spam
## go        3.23e-03 1.04e-03
## until     3.08e-04 2.60e-04
## jurong    3.24e-05 4.33e-05
## point     1.62e-04 4.33e-05
## crazy     1.30e-04 2.60e-04
## available 1.95e-04 1.73e-04</code></pre>
<p>We can also see the prediction scores for each document.</p>
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">nb1</span>, type <span class="op">=</span> <span class="st">"prob"</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># get the predicted document scores</span>
  <span class="va">head</span> <span class="co"># preview predicted probability scores</span></code></pre></div>
<pre><code>##            ham     spam
## text1 1.00e+00 2.25e-08
## text2 1.00e+00 9.58e-05
## text3 3.31e-27 1.00e+00
## text4 1.00e+00 1.23e-08
## text5 1.00e+00 1.66e-11
## text6 5.94e-04 9.99e-01</code></pre>
<p>With the prediction scores for each document, we can transform it so that we can subsequently join the actual class labels for the training dataset. There’s a lot going on in the code below, but the goal is to get model’s prediction for each document in the training dataset and include the model’s probability score.</p>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">nb1_predictions</span> <span class="op">&lt;-</span> 
  <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">nb1</span>, type <span class="op">=</span> <span class="st">"prob"</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># get the predicted document scores</span>
  <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># convert to data frame</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>document <span class="op">=</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/rownames.html">rownames</a></span><span class="op">(</span><span class="va">.</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># add the document names to the data frame</span>
  <span class="fu"><a href="https://tibble.tidyverse.org/reference/as_tibble.html">as_tibble</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># convert to tibble</span>
  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer</a></span><span class="op">(</span>cols <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"ham"</span>, <span class="st">"spam"</span><span class="op">)</span>, <span class="co"># convert from wide to long format</span>
               names_to <span class="op">=</span> <span class="st">"prediction"</span>, <span class="co"># new column for ham/spam predictions</span>
               values_to <span class="op">=</span> <span class="st">"probability"</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># probablity scores for each</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">document</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># group parameter by document</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/slice.html">slice_max</a></span><span class="op">(</span><span class="va">probability</span>, n <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># keep the document row with highest probablity</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/slice.html">slice_head</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># for predictions that were 50/50 </span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">ungroup</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># remove grouping parameter</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>doc_id <span class="op">=</span> <span class="fu"><a href="https://stringr.tidyverse.org/reference/str_remove.html">str_remove</a></span><span class="op">(</span><span class="va">document</span>, <span class="st">"text"</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="va">as.numeric</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># clean up document column so it matches doc_id in</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">doc_id</span><span class="op">)</span> <span class="co"># order by doc_id</span>

<span class="va">nb1_predictions</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/slice.html">slice_head</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">10</span><span class="op">)</span> <span class="co"># preview</span></code></pre></div>
<div class="kable-table">
<table class="table">
<thead><tr class="header">
<th align="left">document</th>
<th align="left">prediction</th>
<th align="right">probability</th>
<th align="right">doc_id</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">text1</td>
<td align="left">ham</td>
<td align="right">1.000</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">text2</td>
<td align="left">ham</td>
<td align="right">1.000</td>
<td align="right">2</td>
</tr>
<tr class="odd">
<td align="left">text3</td>
<td align="left">spam</td>
<td align="right">1.000</td>
<td align="right">3</td>
</tr>
<tr class="even">
<td align="left">text4</td>
<td align="left">ham</td>
<td align="right">1.000</td>
<td align="right">4</td>
</tr>
<tr class="odd">
<td align="left">text5</td>
<td align="left">ham</td>
<td align="right">1.000</td>
<td align="right">5</td>
</tr>
<tr class="even">
<td align="left">text6</td>
<td align="left">spam</td>
<td align="right">0.999</td>
<td align="right">6</td>
</tr>
<tr class="odd">
<td align="left">text7</td>
<td align="left">ham</td>
<td align="right">1.000</td>
<td align="right">7</td>
</tr>
<tr class="even">
<td align="left">text8</td>
<td align="left">ham</td>
<td align="right">1.000</td>
<td align="right">8</td>
</tr>
<tr class="odd">
<td align="left">text9</td>
<td align="left">spam</td>
<td align="right">1.000</td>
<td align="right">9</td>
</tr>
<tr class="even">
<td align="left">text10</td>
<td align="left">spam</td>
<td align="right">1.000</td>
<td align="right">10</td>
</tr>
</tbody>
</table>
</div>
<p>Now with <code>nb1_predictions</code> we can bind the column <code>nb1$y</code> from the model which contains all of the actual (original) class labels with the predictions.</p>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">nb1_predictions_actual</span> <span class="op">&lt;-</span> 
  <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span>actual <span class="op">=</span> <span class="va">nb1</span><span class="op">$</span><span class="va">y</span>, <span class="va">nb1_predictions</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># column-bind actual classes</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">doc_id</span>, <span class="va">document</span>, <span class="va">actual</span>, <span class="va">prediction</span>, <span class="va">probability</span><span class="op">)</span> <span class="co"># organize variables</span>

<span class="va">nb1_predictions_actual</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/slice.html">slice_head</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">5</span><span class="op">)</span> <span class="co"># preview</span></code></pre></div>
<div class="kable-table">
<table class="table">
<thead><tr class="header">
<th align="right">doc_id</th>
<th align="left">document</th>
<th align="left">actual</th>
<th align="left">prediction</th>
<th align="right">probability</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="left">text1</td>
<td align="left">ham</td>
<td align="left">ham</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="left">text2</td>
<td align="left">ham</td>
<td align="left">ham</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="left">text3</td>
<td align="left">spam</td>
<td align="left">spam</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="left">text4</td>
<td align="left">ham</td>
<td align="left">ham</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="left">text5</td>
<td align="left">ham</td>
<td align="left">ham</td>
<td align="right">1</td>
</tr>
</tbody>
</table>
</div>
<p>Now we can cross-tabulate <code>actual</code> and <code>prediction</code> with <code><a href="https://rdrr.io/r/base/table.html">table()</a></code> and send the results to the <code><a href="https://rdrr.io/pkg/caret/man/confusionMatrix.html">confusionMatrix()</a></code> function from the caret package to provide a summary of the model’s performance on the training dataset.</p>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tab_class</span> <span class="op">&lt;-</span> 
  <span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">nb1_predictions_actual</span><span class="op">$</span><span class="va">actual</span>, <span class="co"># actual class labels</span>
        <span class="va">nb1_predictions_actual</span><span class="op">$</span><span class="va">prediction</span><span class="op">)</span> <span class="co"># predicted class labels</span>

<span class="fu">caret</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/caret/man/confusionMatrix.html">confusionMatrix</a></span><span class="op">(</span><span class="va">tab_class</span>, mode <span class="op">=</span> <span class="st">"prec_recall"</span><span class="op">)</span> <span class="co"># model performance statistics</span></code></pre></div>
<pre><code>## Confusion Matrix and Statistics
## 
##       
##         ham spam
##   ham  3582   44
##   spam   18  536
##                                         
##                Accuracy : 0.985         
##                  95% CI : (0.981, 0.989)
##     No Information Rate : 0.861         
##     P-Value [Acc &gt; NIR] : &lt;2e-16        
##                                         
##                   Kappa : 0.937         
##                                         
##  Mcnemar's Test P-Value : 0.0015        
##                                         
##               Precision : 0.988         
##                  Recall : 0.995         
##                      F1 : 0.991         
##              Prevalence : 0.861         
##          Detection Rate : 0.857         
##    Detection Prevalence : 0.867         
##       Balanced Accuracy : 0.960         
##                                         
##        'Positive' Class : ham           
## </code></pre>
<p>So our trained model has a very high accuracy score on the data it was trained on. It’s not perfect, but in practice no algorithm will be. The question now how well this trained model will perform on the new dataset (<code>sms_dfm_test</code>). Let’s now move to test and then evaluate our model’s perform on the <code>sms_dfm_train</code> dataset.</p>
</div>
<div id="model-testing" class="section level3">
<h3 class="hasAnchor">
<a href="#model-testing" class="anchor"></a>Model testing</h3>
<!-- match features and predict classes -->
<p>To test the model we first ensure that the features from the training and test datasets are matched with <code>dfm_matched()</code>. The we use the function <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> to use the <code>nb1</code> model to predict the classes for the <code>sms_dfm_train</code> dataset without the class labels.</p>
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">dfm_matched</span> <span class="op">&lt;-</span> 
  <span class="fu"><a href="https://quanteda.io/reference/dfm_match.html">dfm_match</a></span><span class="op">(</span><span class="va">sms_dfm_test</span>, <span class="co"># test dfm</span>
            features <span class="op">=</span> <span class="fu"><a href="https://quanteda.io/reference/featnames.html">featnames</a></span><span class="op">(</span><span class="va">nb1</span><span class="op">$</span><span class="va">x</span><span class="op">)</span><span class="op">)</span> <span class="co"># (left) join with trained model features</span>

<span class="va">predicted_class</span> <span class="op">&lt;-</span> 
  <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">nb1</span>, <span class="co"># trained model</span>
          newdata <span class="op">=</span> <span class="va">dfm_matched</span><span class="op">)</span> <span class="co"># classify test dataset</span></code></pre></div>
</div>
<div id="evaluation" class="section level3">
<h3 class="hasAnchor">
<a href="#evaluation" class="anchor"></a>Evaluation</h3>
<!-- confusion matrix and scores -->
<p>Let’s now evaluate how well our model performs on the testing dataset.</p>
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">actual_class</span> <span class="op">&lt;-</span> <span class="va">dfm_matched</span><span class="op">$</span><span class="va">sms_type</span>  <span class="co"># get actual class labels</span>

<span class="va">tab_class</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">actual_class</span>, <span class="va">predicted_class</span><span class="op">)</span>  <span class="co"># cross-tabulate actual and predicted class labels</span>

<span class="fu">caret</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/caret/man/confusionMatrix.html">confusionMatrix</a></span><span class="op">(</span><span class="va">tab_class</span>, mode <span class="op">=</span> <span class="st">"prec_recall"</span><span class="op">)</span>  <span class="co"># model performance statistics</span></code></pre></div>
<pre><code>## Confusion Matrix and Statistics
## 
##             predicted_class
## actual_class  ham spam
##         ham  1161   40
##         spam    6  187
##                                         
##                Accuracy : 0.967         
##                  95% CI : (0.956, 0.976)
##     No Information Rate : 0.837         
##     P-Value [Acc &gt; NIR] : &lt; 2e-16       
##                                         
##                   Kappa : 0.871         
##                                         
##  Mcnemar's Test P-Value : 1.14e-06      
##                                         
##               Precision : 0.967         
##                  Recall : 0.995         
##                      F1 : 0.981         
##              Prevalence : 0.837         
##          Detection Rate : 0.833         
##    Detection Prevalence : 0.862         
##       Balanced Accuracy : 0.909         
##                                         
##        'Positive' Class : ham           
## </code></pre>
<p>So we see that the trained <code>nb1</code> model does quite well at 96.7% accuracy. If we did into the cross-tabulation we see that the errors tend to be more for cases when the model predicts that messages are spam when they are in fact ham.</p>
<p>Let’s describe in more detail where the key statistics come from and how they are calculated. Below we have a summary of the meanings of the statistics:</p>
<ul>
<li>Accuracy (measure of overall correct predictions)</li>
<li>Precision (measure of the quality of the predictions)
<ul>
<li>Percentage of predicted ‘ham’ messages that were correct</li>
</ul>
</li>
<li>Recall (measure of the quantity of the predictions)
<ul>
<li>Percentage of actual ‘ham’ messages that were correct</li>
</ul>
</li>
<li>F1-score (summarizes the balance between precision and recall)</li>
</ul>
<p>To calculate these statistic by hand it is helpful to be able to read a confusion matrix as seen in Figure <a href="#fig:eval-confusion-matrix-image">1</a>.</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:eval-confusion-matrix-image"></span>
<img src="images/recipe_10/pda-confusion-matrix.png" alt="Confusion matrix" width="85%"><p class="caption">
Figure 1: Confusion matrix
</p>
</div>
<p>With this in mind we can use the <code>tab_class</code> confusion matrix to extract <code>TP</code>, <code>TN</code>, <code>FP</code>, and <code>FN</code> and create the calculations.</p>
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tab_class</span>  <span class="co"># view confusion matrix</span></code></pre></div>
<pre><code>##             predicted_class
## actual_class  ham spam
##         ham  1161   40
##         spam    6  187</code></pre>
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">N</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">tab_class</span><span class="op">)</span>  <span class="co"># sum of all predictions</span>

<span class="va">TP</span> <span class="op">&lt;-</span> <span class="va">tab_class</span><span class="op">[</span><span class="fl">1</span>, <span class="fl">1</span><span class="op">]</span>  <span class="co"># positive, predicted positive</span>
<span class="va">TN</span> <span class="op">&lt;-</span> <span class="va">tab_class</span><span class="op">[</span><span class="fl">2</span>, <span class="fl">2</span><span class="op">]</span>  <span class="co"># negative, predicted negative</span>

<span class="va">FP</span> <span class="op">&lt;-</span> <span class="va">tab_class</span><span class="op">[</span><span class="fl">1</span>, <span class="fl">2</span><span class="op">]</span>  <span class="co"># negative, predicted positive</span>
<span class="va">FN</span> <span class="op">&lt;-</span> <span class="va">tab_class</span><span class="op">[</span><span class="fl">2</span>, <span class="fl">1</span><span class="op">]</span>  <span class="co"># positive, predicted negative</span>

<span class="co"># Summary statistics</span>

<span class="va">accuracy</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">TP</span> <span class="op">+</span> <span class="va">TN</span><span class="op">)</span><span class="op">/</span><span class="va">N</span>  <span class="co"># higher correct predictions (TP and TN) increase accuracy</span>
<span class="va">precision</span> <span class="op">&lt;-</span> <span class="va">TP</span><span class="op">/</span><span class="op">(</span><span class="va">TP</span> <span class="op">+</span> <span class="va">FP</span><span class="op">)</span>  <span class="co"># lower FP increases precision</span>
<span class="va">recall</span> <span class="op">&lt;-</span> <span class="va">TP</span><span class="op">/</span><span class="op">(</span><span class="va">TP</span> <span class="op">+</span> <span class="va">FN</span><span class="op">)</span>  <span class="co"># lower FN increases recall</span>

<span class="va">f1_score</span> <span class="op">&lt;-</span> <span class="fl">2</span> <span class="op">*</span> <span class="op">(</span><span class="op">(</span><span class="va">precision</span> <span class="op">*</span> <span class="va">recall</span><span class="op">)</span><span class="op">/</span><span class="op">(</span><span class="va">precision</span> <span class="op">+</span> <span class="va">recall</span><span class="op">)</span><span class="op">)</span></code></pre></div>
</div>
<div id="production" class="section level3">
<h3 class="hasAnchor">
<a href="#production" class="anchor"></a>Production</h3>
<!-- function to apply to new text -->
<p>Now, if we were satisfied with this model and wanted to put it into use to filter real SMS text messages, we could create a function to do just that.</p>
<p>We just need to include the step to tokenize the new message in the same way we did to create the model and then create a dfm of these tokens as features. Then we match the features from the model and apply the model to the new message and report the class prediction as the result.</p>
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">predict_sms_type</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">sms_message</span>, <span class="va">nb_model</span><span class="op">)</span> <span class="op">{</span>
  <span class="co"># Function</span>
  <span class="co"># Takes a character vector of sms messages and provides</span>
  <span class="co"># a prediction as to whether the review is spam or ham</span>
  <span class="co"># given the given trained NB model</span>
  
  
<span class="va">sms_tokens</span> <span class="op">&lt;-</span> 
  <span class="fu"><a href="https://quanteda.io/reference/tokens.html">tokens</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">sms_message</span>, <span class="co"># character vector</span>
         what <span class="op">=</span> <span class="st">"word"</span>, <span class="co"># tokenize by words</span>
         remove_punct <span class="op">=</span> <span class="cn">TRUE</span>, <span class="co"># remove punctuation</span>
         remove_numbers <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># remove numbers</span>
  <span class="fu"><a href="https://quanteda.io/reference/tokens_tolower.html">tokens_tolower</a></span><span class="op">(</span><span class="op">)</span> <span class="co"># lowercase all characters</span>

<span class="va">sms_dfm</span> <span class="op">&lt;-</span> 
  <span class="fu"><a href="https://quanteda.io/reference/dfm.html">dfm</a></span><span class="op">(</span><span class="va">sms_tokens</span><span class="op">)</span> <span class="co"># create a document-frequency matrix</span>
  
  <span class="co"># Match features from the Naive Bayes model</span>
  <span class="va">dfm_matched</span> <span class="op">&lt;-</span> 
    <span class="fu"><a href="https://quanteda.io/reference/dfm_match.html">dfm_match</a></span><span class="op">(</span><span class="va">sms_dfm</span>, features <span class="op">=</span> <span class="fu"><a href="https://quanteda.io/reference/featnames.html">featnames</a></span><span class="op">(</span><span class="va">nb_model</span><span class="op">$</span><span class="va">x</span><span class="op">)</span><span class="op">)</span>
  
  <span class="co"># Predict class for the given review</span>
  <span class="va">predicted_class</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">nb_model</span>, newdata <span class="op">=</span> <span class="va">dfm_matched</span><span class="op">)</span>
  
  <span class="fu"><a href="https://rdrr.io/r/base/character.html">as.character</a></span><span class="op">(</span><span class="va">predicted_class</span><span class="op">)</span>
<span class="op">}</span>


<span class="fu">predict_sms_type</span><span class="op">(</span>sms_message <span class="op">=</span> <span class="st">"Hey how's it going?"</span>, nb_model <span class="op">=</span> <span class="va">nb1</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "ham"</code></pre>
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">predict_sms_type</span><span class="op">(</span>sms_message <span class="op">=</span> <span class="st">"Call now to order this amazing product!!"</span>, nb_model <span class="op">=</span> <span class="va">nb1</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "spam"</code></pre>
<p>As you can see we can now create our own text messages and have them filtered by the algorithm that we have developed here.</p>
</div>
</div>
<div id="summary" class="section level2">
<h2 class="hasAnchor">
<a href="#summary" class="anchor"></a>Summary</h2>
<p>In this Recipe, I demonstrated the steps involved in creating a text classification model. We then evaluated the training model and then applied it to the test data. The evaluation of both the training and testing predictions show that they were highly accurate. Since these results were very promising I demonstrated how we can turn a trained model into an actual spam filter.</p>
<p>Below I’ve included the code summary of the necessary steps to implement this prediction model.</p>
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Get SMS dataset ---</span>
<span class="va">sms_df</span> <span class="op">&lt;-</span> <span class="fu">tadr</span><span class="fu">::</span><span class="va"><a href="../reference/sms.html">sms</a></span> <span class="co"># load dataset from tadr package</span>

<span class="co"># Create corpus object ---</span>
<span class="va">sms_corpus</span> <span class="op">&lt;-</span> <span class="co"># quanteda corpus object</span>
  <span class="fu"><a href="https://quanteda.io/reference/corpus.html">corpus</a></span><span class="op">(</span><span class="va">sms_df</span>, <span class="co"># data frame</span>
         text_field <span class="op">=</span> <span class="st">"message"</span><span class="op">)</span> <span class="co"># text field</span>

<span class="va">sms_corpus</span><span class="op">$</span><span class="va">doc_id</span> <span class="op">&lt;-</span> <span class="co"># create a new column `doc_id`</span>
  <span class="fl">1</span><span class="op">:</span><span class="fu"><a href="https://quanteda.io/reference/ndoc.html">ndoc</a></span><span class="op">(</span><span class="va">sms_corpus</span><span class="op">)</span> <span class="co"># add numeric id to each text message</span>

<span class="co"># Create tokens object</span>
<span class="va">sms_tokens</span> <span class="op">&lt;-</span> 
  <span class="fu"><a href="https://quanteda.io/reference/tokens.html">tokens</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">sms_corpus</span>, <span class="co"># corpus object</span>
         what <span class="op">=</span> <span class="st">"word"</span>, <span class="co"># tokenize by words</span>
         remove_punct <span class="op">=</span> <span class="cn">TRUE</span>, <span class="co"># remove punctuation</span>
         remove_numbers <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># remove numbers</span>
  <span class="fu"><a href="https://quanteda.io/reference/tokens_tolower.html">tokens_tolower</a></span><span class="op">(</span><span class="op">)</span> <span class="co"># lowercase all characters</span>

<span class="co"># Create testing/ training splits</span>
<span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">300</span><span class="op">)</span> <span class="co"># make reproducible</span>

<span class="va">num_docs</span> <span class="op">&lt;-</span> 
  <span class="va">sms_dfm</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># dfm object</span>
  <span class="fu"><a href="https://quanteda.io/reference/ndoc.html">ndoc</a></span><span class="op">(</span><span class="op">)</span> <span class="co"># get number of documents</span>

<span class="va">train_size</span> <span class="op">&lt;-</span> 
  <span class="op">(</span><span class="va">num_docs</span> <span class="op">*</span> <span class="fl">.75</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># get size of sample</span>
  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="op">)</span> <span class="co"># round to nearest whole number</span>

<span class="va">train_ids</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="va">num_docs</span>, <span class="co"># population</span>
                   size <span class="op">=</span> <span class="va">train_size</span>, <span class="co"># size of sample</span>
                   replace <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="co"># without replacement</span>
<span class="va">sms_dfm_train</span> <span class="op">&lt;-</span> 
  <span class="va">sms_dfm</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># dfm object</span>
  <span class="fu"><a href="https://quanteda.io/reference/dfm_subset.html">dfm_subset</a></span><span class="op">(</span><span class="va">doc_id</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="va">train_ids</span><span class="op">)</span> <span class="co"># subset matching doc_id and train_ids</span>

<span class="va">sms_dfm_test</span> <span class="op">&lt;-</span> 
  <span class="va">sms_dfm</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># dfm object</span>
  <span class="fu"><a href="https://quanteda.io/reference/dfm_subset.html">dfm_subset</a></span><span class="op">(</span><span class="op">!</span><span class="va">doc_id</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="va">train_ids</span><span class="op">)</span> <span class="co"># subset non-matching doc_id and train_ids</span>

<span class="co"># Train the NB model</span>
<span class="va">nb1</span> <span class="op">&lt;-</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/quanteda.textmodels/man/textmodel_nb.html">textmodel_nb</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">sms_dfm_train</span>, <span class="co"># document-feature matrix</span>
               y <span class="op">=</span> <span class="va">sms_dfm_train</span><span class="op">$</span><span class="va">sms_type</span><span class="op">)</span> <span class="co"># class labels</span>

<span class="co"># Test the NB model</span>
<span class="va">dfm_matched</span> <span class="op">&lt;-</span> 
  <span class="fu"><a href="https://quanteda.io/reference/dfm_match.html">dfm_match</a></span><span class="op">(</span><span class="va">sms_dfm_test</span>, <span class="co"># test dfm</span>
            features <span class="op">=</span> <span class="fu"><a href="https://quanteda.io/reference/featnames.html">featnames</a></span><span class="op">(</span><span class="va">nb1</span><span class="op">$</span><span class="va">x</span><span class="op">)</span><span class="op">)</span> <span class="co"># (left) join with trained model features</span>

<span class="va">predicted_class</span> <span class="op">&lt;-</span> 
  <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">nb1</span>, <span class="co"># trained model</span>
          newdata <span class="op">=</span> <span class="va">dfm_matched</span><span class="op">)</span> <span class="co"># classify test dataset</span>

<span class="co"># Evaluate model performance</span>
<span class="va">actual_class</span> <span class="op">&lt;-</span> 
  <span class="va">dfm_matched</span><span class="op">$</span><span class="va">sms_type</span> <span class="co"># get actual class labels</span>

<span class="va">tab_class</span> <span class="op">&lt;-</span> 
  <span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">actual_class</span>, <span class="va">predicted_class</span><span class="op">)</span> <span class="co"># cross-tabulate actual and predicted class labels</span>

<span class="fu">caret</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/caret/man/confusionMatrix.html">confusionMatrix</a></span><span class="op">(</span><span class="va">tab_class</span>, mode <span class="op">=</span> <span class="st">"prec_recall"</span><span class="op">)</span> <span class="co"># model performance statistics</span></code></pre></div>
</div>
<div id="references" class="section level2">
<h2 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h2>
<!-- DRAFTS -->
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-Almeida2011" class="csl-entry">
Almeida, Tiago A., and Jos’e María G’omez Hildago. 2011. <span>“SMS Spam Collection.”</span> <em>SMS Spam Collection v. 1</em>. https://www.dt.fee.unicamp.br/~tiago/smsspamcollection/.
</div>
<div id="ref-R-quanteda" class="csl-entry">
Benoit, Kenneth, Kohei Watanabe, Haiyan Wang, Paul Nulty, Adam Obeng, Stefan Müller, Akitaka Matsuo, and William Lowe. 2021. <em>Quanteda: Quantitative Analysis of Textual Data</em>. <a href="https://quanteda.io">https://quanteda.io</a>.
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Jerid Francom.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
